### ISSUE TITLE
Number fields do not return a value

### ISSUE THREAD

**Issue by jncart** [forcePanda/Flow-Repo#5]
Passing a number field into the action will result in a null output value. I believe the problem is this section:

`        switch on fieldType {//Setting Field value based on the field data type
            when BOOLEAN {
                output.booleanOutput = (Boolean) fieldValue;
            }
            when CURRENCY {
                output.currencyOutput =(Decimal) fieldValue;
            }
            when INTEGER {
                output.numberOutput = (Integer) fieldValue;
            }
            when DATE {
                output.dateOutput = (Date) fieldValue;
            }
            when DATETIME {
                output.datetimeOutput = (DateTime) fieldValue;
            }
        }
        return output;
    }`

INTEGER should be DOUBLE and return a Decimal value.

**Comment by forcePanda** [comment]
Hi,

Can you please mention which action flow action are you referring to?

**Comment by jncart** [comment]
Dynamic Field Value from SObject Record

**Comment by forcePanda** [comment]
That's odd. Because the tests, which include a Number field, are passing.

Have you tried it already?

**Comment by tkgbpt** [comment]
Hi @forcePanda , I've just started using this component (Dynamic Field Value from SObject Record), and hit upon this same issue. That's even though I am not actually using currency or number fields in my Flow, but I am getting the issue precisely BECAUSE the tests are not passing:

> System.AssertException: Assertion Failed: Unexpected currency output.: Expected: 100, Actual: null
> System.AssertException: Assertion Failed: Unexpected number output.: Expected: 5, Actual: null

Which means the entire component is currently not usable, because the test failure is preventing deployment to Production orgs.

To get around this, I have just commented out the currency and number assert statements in the test class for now, but obviously that's not a good solution - any thoughts? Thank you!!

**Comment by forcePanda** [comment]
You must have tempered with the code I'm guessing because the tests are passing on my org.
I anyway had to fix the Partner community reference and created it as an unlocked package.

Checkout the readme file for the newest version.
https://github.com/forcePanda/Flow-Repo/blob/master/Apex%20Actions/Dynamic%20Field%20Value%20from%20SObject%20Record/README.md
